# Generated by Django 4.1.6 on 2023-02-09 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("thermostixapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="log",
            name="thermometer",
        ),
        migrations.AddField(
            model_name="log",
            name="thermometer",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="thermostixapp.thermometer",
            ),
            preserve_default=False,
        ),
    ]
